### ISSUE TITLE
MA-XML-7.0-CATALAN

### ISSUE THREAD

**Issue by calanor** [deivids84/MA-XML-7.0-CATALAN#11]
Crec que tindries que renombrar el repositori a MA-XML-7.0-CATALAN

**Comment by deivids84** [comment]
Tens tota la raó, que ja ha sortit l'estable amb MiUI 7. Ara ho faig.

**Comment by perahtus** [comment]
Primer de tot, moltes gràcies per la traducció. He vist que a l'última versió estable (7.0.6.0) no puc escollir català, pot ser que sigui per aquest motiu?

**Comment by calanor** [comment]
Si,
de moment el català el trobaràs en les setmanals. No se si en la propera estable ja sortirà el català.

**Comment by deivids84** [comment]
Es que quan va sortir l'estable encara no els hi havia passat als de xiaomi.eu. Suposo que a la propera ja sortirà

**Comment by perahtus** [comment]
Perfecte, gràcies!
