### ISSUE TITLE
framework-res.apk / error: Apostrophe not preceded by \

### ISSUE THREAD

**Issue by usnkreal** [deivids84/MA-XML-7.0-CATALAN#18]
https://github.com/deivids84/MA-XML-7.0-CATALAN/blob/master/Catalan/main/framework-res.apk/res/values-ca/strings.xml
strings.xml:677
strings.xml:680
strings.xml:704
strings.xml:721
strings.xml:735
strings.xml:754
Fixed here https://www.dropbox.com/s/huqhrsr9n4b5gle/strings.zip?dl=0

**Comment by deivids84** [comment]
Ok. Thanks.
