### ISSUE TITLE
possible error de tancament de music

### ISSUE THREAD

**Issue by mar-ff** [deivids84/MA-XML-7.0-CATALAN#25]
línies 155, 193, 389 al fitxer:
(les línies 277 i 417 en Anglès també n'hi ha però ho dibuixa diferent, no se si és un altre caràcter.)

https://github.com/deivids84/MA-XML-7.0-CATALAN/blob/master/Catalan/main/Music.apk/assets/lang/lang.ca.js

sembla que no està traduït, però hi ha algun "D\'acord" que podria ser el problema, ja que pel que veig al que apareix amb Anglès, per a ficar un apòstrof ulitiza &apos; i a sobre, com està entre dobles comentes, suposo que no caldria ficar la barra invertida, però al ser java script igual no li agrada que hi hagi solament una cometa simple i no es tanqui.

**Comment by deivids84** [comment]
D'acord. Torno a deixar l'original a veure si corregim l'error. Gracies

**Comment by mar-ff** [comment]
Per cert, vaig provar d'esborrar les dades del programa de música, i ja funciona bé.
