### ISSUE TITLE
Galeria i càmera selfie

### ISSUE THREAD

**Issue by JS67** [deivids84/MA-XML-7.0-CATALAN#28]
Hola, 
El tema que la galeria no carrega imatges he vist en un foro que se soluciona canviant l'idioma a anglès primer, i després tornar a espanyol....però en català NO funciona!!! Pot ser? A algú mes li passa?
Per altra banda, la càmera de selfies fa les fotos al revés, us heu fixat? Hi ha alguna opció (com antigament sí hi havia) d' "efecte mirall"?
Finalment, moltes gràcies per la traducció al català, està molt bé!!!
Salutacions,

**Comment by deivids84** [comment]
Hola,
A mi tambè em passa, però no he trobat cap error a la traducció. El tema selfies a mi em funciona perfecte sense efecte mirall.  No sembla que sigui problema de les traduccions.
Salutacions

**Comment by JS67** [comment]
Hola, David

Gràcies per respondre tant ràpid. Potser no m'he explicat bé, no qüestiono
la traducció, al contrari, la trobo molt bona!
En quan a la galeria, la veritat és que és molest, per això he tornat a
l'espanyol i ara em va bé. No vull dir que la traducció estigui malament,
però el fet és que en castellà, un cop l'has posat en anglès una vegada
(tal com diuen en els foros), va bé.
La veritat és que després d'un any amb ROMS de miui.es on no hi ha català,
ahir vaig provar aquesta i em vaig quedar gratament satisfet que existís el
català com a opció (no ho sabia). Quan el tema de la galeria estigui
arreglat el tornaré a posar en català.
I en quan a la càmera, és una xorrada, ja ho sé, però trobo curiós aquest
efecte. A casa tenim 3 xiaomis amb 3 ROMs diferents i tots la fan igual.
Això ho soluciono amb una app (Camera 360) en la que tens la opció de
"Efecte mirall", així potser fer selfies del dret i del revés, hahahahhaha
Tot va venir perquè la ROM que portava em perdia la connexió de dades quan
es recuperava d'una manca de cobertura i havia de reiniciar. Per aquest
motiu vull provar aquesta que encara no he testejat si em passarà això,
encara no s'ha donat el cas...
Res més, que moltíssimes gràcies per tot!!!
Salut!

Este correo electrónico se ha enviado desde un equipo libre de virus y
protegido por Avast.
www.avast.com
https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-02-28 16:24 GMT+01:00 David Capdevila notifications@github.com:
