### ISSUE TITLE
Error connexió de dades

### ISSUE THREAD

**Issue by JS67** [deivids84/MA-XML-7.0-CATALAN#30]
Hola, 
No té res a veure amb la traducció, però tinc un seriós problema amb la connexió de dades, ja que aquesta es perd quan es recupera d'una manca de cobertura i haig de reiniciar. 
A algú li passa alguna cosa semblant i ha trobat la solució?
Gràcies!

**Comment by deivids84** [comment]
A mi no m'ha passat mai, tot i que a vegades li costa una mica recuperar, però sempre menys de 30 segons. El que em comentaves de la galeria ja ho vaig corregir. A la actualització d'avui ja va bé.

**Comment by DaWy** [comment]
El que comentes m'ha passat alguna vegada amb la ROM MIUI, molt aleatoriament. Pero ara no porto la MIUI, porto la CM 6.0, aixi que no puc ajudarte gaire. Em sona haver vist mes gent amb aquest problema a htcmania.
