### ISSUE TITLE
Petició recomiplació ROM

### ISSUE THREAD

**Issue by nest88** [deivids84/MA-XML-7.0-CATALAN#31]
Hola,

Podries demanar la recompilació de la ROM del Xiaomi Redmi 3 estable 7.1 perquè té el mateix error amb la galeria i la càmera i actualment no hi ha més versions del les estables. Així quedaria arreglat.

Moltes gràcies!

**Comment by deivids84** [comment]
Hola nest88!

Perdona per contestar tant tard, no havia vist el missatge. El dia 20 (el teu missatge es del dia 19) va sortir la nova actualització de l'estable 7.2.
Espero que amb aquesta actualització et vagi tot perfecte. Per qualsevol altre error de traducció, que n'hi ha molts, m'ho fas saber per una traducció cada cop més bona.

Moltes gràcies!

**Comment by nest88** [comment]
Hola, 
Demano la recopilació per culpa del bootloader bloquejat, ja que la 7.2 encara no es pot instalar per mi Flash i download. En principi estic l'espera del codi de desbloqueig però mentrestant volia gaudir del telèfon en català

**Comment by deivids84** [comment]
Hola nest88,
Aquí no hi puc fer res, el que et vaig comentar ahir és el que em van respondre a mi. A veure si t'arriba aviat el codi de desbloqueig i pots posar el telèfon en català. Espero els teus comentaris de millora de la traducció. 
Gràcies.
