### ISSUE TITLE
Text no traduït a les versions 6.3.17 i 6.3.24

### ISSUE THREAD

**Issue by JS67** [deivids84/MA-XML-7.0-CATALAN#32]
Hola, jo vaig amb la 6.3.3. perquè està perfectament traduïda però té el problema que no carrega la galeria. 
He provat les posteriors (6.3.17 i 6.3.24) en les que això ja està arreglat, però he vist que té molts textos sense traduir sobre tot a la galeria i a les opcions de foto i per això torno a la 6.3.3
En quina versió es tornarà a traduir tot?
No sé si aquests dubtes es posen aquí. Si no és així, disculpeu i digueu-me on es poden reportar aquestes incidències. I si puc ajudar en qualsevol cosa....
Moltes gràcies per endavant!

**Comment by deivids84** [comment]
Hola JS67!

Em pots definir exactament que es el que et surt que no està traduït i quin model de telèfon tens?
Jo tradueixo a partir de la base del Mi Note que és el que tinc jo i em surt tot traduït, menys la part de recompte de dades que es el que volia arreglar avui, per la propera actualització.
Espero la teva resposta a veure si aconseguim que el proper divendres ho puguis tenir solucionat
Els vostres comentaris son la millor ajuda per poder anar perfeccionant la traducció al català.
Moltes gràcies!

**Comment by JS67** [comment]
Hola deivids84
Gràcies per la teva ràpida resposta. 
El meu model és Redmi Note 4G (1SIM). No puc pujar prova perquè ja he restaurat la versió anterior sense haver fet captura de pantalla,però recordo que era:
- A la galeria, 2 opcions: "Phone" i "Album", i abaix posava "New Album". Apart que el disseny no m'agrada tant com el de la 6.3.3. on les opcions són: Fotos - Local - Núvol - Gent.
- A les opcions de la foto "Send" "Edit" "Delete" i "More" i dintre "More" : de les 6 opcions, almenys 4 no estaven traduïdes, ara no recordo quines..
- A les opcions del navegador, ara hi veig "Add bookmark" "Manage downloads" i "Refresh", i a 6.3.24. es veia traduït però tallat, la segona línia no es llegia...

La 6.3.3. la vaig instal·lar amb tots el wipes (instal·lació neta) i les posteriors les actualitzo "sobre" aquesta, només amb wipes dalvik i cache. Pot tenir a veure alguna cosa?

Per altra banda, veig que hi ha la versió estable 7.2, la recomanes? Es pot instal·lar sobre una setmanal? O s'ha de fer instal·lació neta?

Moltes gràcies

**Comment by deivids84** [comment]
Perfecte JS67!

A mi em surt tot correcte, ara vaig a repassar la base del Redmi Note 4G a veure si ho puc solucionar. 

Respecte a les instal·lacions, jo només vaig fer una neta quan vaig passar de Kitkat a Marshmallow i de moment tot perfecte, encara que és recomanable fer-ho.
Jo l'estable no l'he provat, sempre porto la setmanal per poder anar controlant les traduccions. 

Moltes gràcies!

![screenshot_2016-03-25-12-06-30_com android browser](https://cloud.githubusercontent.com/assets/13929105/14043301/fb67248a-f282-11e5-8508-6f43442fdc94.png)
![screenshot_2016-03-25-12-07-38_com miui gallery](https://cloud.githubusercontent.com/assets/13929105/14043302/fb671878-f282-11e5-8be5-ec0248924431.png)
![screenshot_2016-03-25-12-08-05_com miui gallery](https://cloud.githubusercontent.com/assets/13929105/14043303/fb677ba6-f282-11e5-8d4d-5c190555fcdc.png)

**Comment by deivids84** [comment]
Ei! 
Ja m'he estat mirant les bases i veig que les dels telèfons Redmi i les dels telèfons Mi són diferents. Vaig a fusionar les dues. 
Gràcies!

**Comment by JS67** [comment]
Hola deivids84
Perfecte! Provaré divendres que ve, a veure si ja està bé.
EL que trobo curiós és que veig la galeria diferent. En la teva captura es veu com la veig jo ara amb la 6.3.3. però en les posteriors hi veig només 2 opcions (Phone i Album) i amb un disseny diferent...
Per cert, ja que hi som (jejejejeje), a contactes veig "Add" enlloc d'"Afegir" o "Nou".
Moltes gràcies per la teva implicació!!!

**Comment by JS67** [comment]
Ostres, mentre t'escrivia he vist que em deies que has vist que els bases Redmi-Mi són diferents. Perfecte!!! Es podran fusionar? 
A Redmi Note encara anem amb Android 4.4
Moltes gràcies, daivids84!

**Comment by deivids84** [comment]
Bon dia JS67! 

Fins ahir a la nit no ho vaig poder repassar.  
De moment només he trobat la galeria amb unes 200 línies diferents Redmi-Mi. Ja està corregit i enviat a xiaomi.eu. 
El que em comentes de contactes el vaig corregir a l'actualització del dia 13.
Continuo repassant per corregir més errors per el proper divendres. 
Gràcies!

**Comment by nest88** [comment]
A la última de desenvolupador hi falten les següents traduc
![screenshot_2016-03-26-10-42-07_com miui gallery](https://cloud.githubusercontent.com/assets/17708151/14059406/3fb69bee-f340-11e5-87dc-b434d38be4d7.png)
![screenshot_2016-03-26-10-41-54_com miui gallery](https://cloud.githubusercontent.com/assets/17708151/14059409/4e8c5cda-f340-11e5-95b9-d381fb081e4f.png)

cions. També a l'inici de la  galeria a dalt posa Photo Album i a baix new album

**Comment by deivids84** [comment]
Hola nest88! 
Ahir el vespre vaig afegir 200 noves línies a la galeria.  Com li vaig comentar a en JS67, jo treballava des de la base del Mi Note, però ahir em va fer adonar que els Redmi tenen coses diferents. Estic repassant totes les traduccions per la propera actualització. Si trobes algun error fora de la galeria, ja m'ho faràs saber. 
Gràcies

**Comment by JS67** [comment]
Perfecte! A veure si entre tots ho aconseguim. Divendres que ve actualitzaré i aniré reportant els errors (si n'hi ha...). Ara ja sabem què passa. Estic molt content! Moltíssimes gràcies deivids 84 i nest88!!!

**Comment by JS67** [comment]
Algunes cosetes més:
- La consulta de l'Agenda des del calendari mostra la data en format anglès. És a dir, per a 29 de març mostra 03.29 en lloc de 29.03.
- A la barra de Cerca hi surten lletres xineses.
- A Configuració addicional - LED de notificació - "Light up when charging".
- A Configuració addicional - Botons - "Automatically disable navigation buttons"
- Al widget del Calendari - Més - Configuració - "User notification"

I el tema de l'efecte mirall a la càmera davantera (selfie) continua....A versions anteriors hi havia la opció d'activar-ho o no i ara ha desaparegut (fa les selfies al revés), però no crec que es solucioni amb la fusió de Redmi - Mi, no? 

Moltíssimes gràcies!!!

**Comment by deivids84** [comment]
No,  jo l'únic que puc fer es traduir textos, però no activar opcions.  El que pots fer és anar a l'app d'informar d'error,  càmera i enviar allà l'error. Haurà de ser amb anglès perquè va directe a Xiaomi. 
 Ahir el vespre vaig acabar de repassar i han afegit unes 12000 línies noves. Intentaré fer les que em passeu primer, però tinc feina per un parell de mesos. 
Gràcies per la vostra col·laboració.

**Comment by JS67** [comment]
OK, ho provaré..
Per altra banda, quina feinada se t'ha girat...per cert, si puc ajudar en alguna cosa només cal que m'ho diguis.

**Comment by nest88** [comment]
Si, jo crec que depèn de com et podem donar un cop de mà, encara que sigui la traducció i tu les repasses perquè tens les paraules que has anat posant a totes les línies

**Comment by deivids84** [comment]
Perfecte @nest88 i @JS67! 

Si us sembla bé ens trobem a la plataforma crowdin, allà em trobareu en el projecte MIUI 7. Continuem parlant per allà!
