### ISSUE TITLE
Errades

### ISSUE THREAD

**Issue by Miroure** [deivids84/MA-XML-7.0-CATALAN#33]
Penso que la traducció al català es podria millorar (evitant l'ús d'infinitius, faltes ortogràfiques,...)
Si vols escriu-me a robert.serra@aol.com  i ho comentem

**Comment by deivids84** [comment]
Si, ja ho sé. No tinc temps d'anar corregint i afegint les noves línies. Si t'hi vols afegir, jo encantat 😉

**Comment by Miroure** [comment]
Et puc ajudar.
He traduït altres programes seguint les normes de Softcatalà.

Pots enviar-me  un fitxer amb totes les línies ? (que es pugui obrir i
editar amb el bloc de notes o similar)

O esperem que ara el juny surt una nova Rom i comencem a partir d'aquesta?

2016-05-29 18:09 GMT+02:00 David Capdevila notifications@github.com:

**Comment by deivids84** [comment]
Genial

Des de aquí és pot fer tot. Només cal que toquis el botó fork i des de el programa Github Desktop ja podràs fer la còpia al Pc i publicar els canvis. 

La Rom del juny farà servir els mateixos arxius de traducció.

Quan ho tinguis fet, continuem parlant.

**Comment by Miroure** [comment]
He baixat i instal·lat el Github Desktop.
He executat el fitxer que has creat de l'idioma català.

Veig que el GitHub és una mena d'editor amb control de versions (diria),
però no entenc (no sóc informàtic) com està arxivat ni com saber per on ja
ho he revisat/corregit

Perquè algunes línies tenen la lletra vermella?
També hi ha línies amb fons verd i vermell.
Encara no he trobat com editar-ho, només visualitzar-ho.
Veig que davant d'un apòstrof hi poses una .
Hi ha altres normes que hagi de saber?

Suposo que treballar amb aquest sistema deu ser molt millor. Però ara
mateix no sé com fer-ho.

Altres vegades quan traduïa un programa, rebia un sol fitxer.
Hi ha la possibilitat que m'enviïs un sol fitxer?
O haurem de quedar per fer una sessió de Teamviewer o Skype i m'ho ensenyes
remotament.

Bona nit

El dia 29 de maig de 2016, 18:50, David Capdevila notifications@github.com
ha escrit:

**Comment by deivids84** [comment]
Perfecte

El GitHub Desktop només serveix per sincronitzar els teus fitxers amb els
de la plataforma.

El moment que has sincronitzat la teva forquilla amb el GitHub Desktop,
t'ha demanat on volies guardar la còpia al teu ordinador.

El més segur és que sigui a Documents amb el nom de
Miroure/MA-XML-7.0-CATALAN.

Jo per editar faig servir el programa Notepad++, és més fàcil ja que et
surt el codi igual que al GitHub. De tot el codi només s'ha de modificar la
part negre.

Jo amb el GitHub també tinc clonat el repositori principal que és
https://github.com/Acid-miuipolskapl/v6-XML-Compare i faig servir la base
de gemini. A partir d'aquí es tractà d'obrir el mateix document de la base
i el català, anar comparant, borrar les línies velles, afegir les noves i
corregir les que estiguin mal traduïdes.

PD: Si ho veus molt complicat fem això que dius, et passo els 2 fitxers (català + base) de l'aplicació que vulguis.

El dl., 30 maig 2016 , 10:10 p. m., Miroure notifications@github.com va
escriure:

**Comment by Miroure** [comment]
He començat a correcció, però em caldria el fitxer original en anglès
d'aquesta mateixa versió per  a poder comprovar-lo?
Com puc baixar-lo?
A Xiaomi.eu hi ha altre idiomes però la versió en anglès no sé com
baixar-la (si que puc baixar l'italià, francés,...)

El dia 31 de maig de 2016, 7:17, David Capdevila notifications@github.com
ha escrit:

**Comment by deivids84** [comment]
Tens l'enllaç en la resposta anterior

**Comment by Miroure** [comment]
Consulta:

Com és que a la versió x6-XML-Compare-master (gemini o gemini_stable) no hi
ha la carpeta per exemple:

keyguardmusicview
powermenu
statusbar_music

I sí que hi són a la versió en català?
Per tant no tinc la versió original en anglès per a poder repassar-ho.

2016-05-31 23:15 GMT+02:00 David Capdevila notifications@github.com:

**Comment by Miroure** [comment]
A la carpeta: statusbar_music. Hi ha la següent traducció:

_<?xml version="1.0"?>_

_-<strings>_

_<string value="Obrir reproductor de Música" name="no_title"/>_

_<string value="Sense música" name="no_artist"/>_
_</strings>_

Semblaria que la traducció no és correcte. Exemple:
_No title > obrir el reproductor_   ??????

Però com que a la versió Compare-master  aquest fitxer no hi és, no sé si
està ben traduït.

2016-06-05 6:32 GMT+02:00 Miquel Roure miroure@gmail.com:

**Comment by deivids84** [comment]
Mira la espanyola

https://github.com/ingbrzy/MA-XML-7.0-SPANISH

**Comment by Miroure** [comment]
Ja he mirat les versions espanyola i l'italiana.
L'espanyola ho tradueix igual que el català
L'italiana no ho tradueix (ho deixa en blanc)
Però semblaria que traduïr\* No_title\*  per *Obre el reproductor de música *no
té cap ni peus.

2016-06-05 7:36 GMT+02:00 David Capdevila notifications@github.com:

**Comment by deivids84** [comment]
Com que no tenim la base en anglès, fem cas a l'espanyola que si els usuaris espanyols (que en té molts) no s'han queixat, senyal que algun sentit té. 

Pensa en anar publicant les modificacions constantment i anar actualitzant la base i la catalana.

**Comment by deivids84** [comment]
Veig que son dues carpetes que ja no s'utilitzen. Es poden esborrar. 

Codi de powermenu

> <resources>

```
<string name="label_airplane_mode">Airplane</string>
<string name="label_silent_mode">Silent</string>
<string name="label_reboot">Reboot</string>
<string name="label_shutdown">Power off</string>
<string name="label_alert_reboot">Tap to reboot</string>
<string name="label_alert_shutdown">Tap to power off</string>
<string name="label_blank">Back</string>
```

> </resources>

**Comment by deivids84** [comment]
Ha canviat la base https://github.com/Acid-miuipolskapl/v8-XML-Compare

**Comment by Miroure** [comment]
Gràcies per informar-me. Hauré de comparar quin fitxers són iguals amb els
que ja he corregit.

2016-06-09 13:55 GMT+02:00 David Capdevila notifications@github.com:

**Comment by deivids84** [comment]
Els has publicat al github?

**Comment by Miroure** [comment]
No

2016-06-09 14:33 GMT+02:00 David Capdevila notifications@github.com:

**Comment by Miroure** [comment]
Perdona que et pregunti coses, però ja et vaig dir que no sóc informàtic i
hi ha coses que ...

He baixat la nova base de l'enllaç que em vas enviar ahir v.8
Però la versió en català que hi ha penjada és la v.7
M'he esperar a baixar la versió v.8 en català quan estigui penjada?

Hi ha alguna manera de modificar la versió en català en línia? És a dir
sense baixar el fitxer?
Hi ha alguna manera que hi hagin tots el fitxers en català per exemple al
Google Drive i tothom amb l'enllaç i pugui entrar i editar, i després una
sola persona pugui els fitxers al Github?

2016-06-09 14:41 GMT+02:00 Miquel Roure miroure@gmail.com:

**Comment by leixet** [comment]
Companys, no sé de quan de temps disposaré, però m'interessa molt involucrar-me en aquesta traducció. Sóc membre de Softcatalà així que si tinc temps i m'apanyo amb el github puc intentar  repassar totes les cadenes perquè segueixin la guia d'estil de Softcatalà i tinguin coherència i cohesió entre elles. A veure si ara que ve l'agost m'hi poso a fons. Ens repartim la feina d'alguna manera? Com ho veieu?

**Comment by Miroure** [comment]
Jo vaig començar amb la revisió/correcció del fitxer Settings de la versió
8 i ja vaig enviar aproximadament les primeres 400 línies.
No sé si ja s'han pujat.

Potser aniria bé d'acabar aquest fitxer o sinò que en David triï quin fem.
Jo hi dedico les hores quan puc.

Miquel

El dia 28 de juliol de 2016, 14:57, leixet notifications@github.com ha
escrit:

**Comment by leixet** [comment]
Em sembla bé Miquel. Jo podré començar a mirar-m'ho la setmana q ve.

Estem parlant de MIUI 8, oi? Com que en alguns dispositius, com el Mi 5, la versió estable de la rom de xiaomi.eu segueix en MIUI 7, també estaria bé revisar les cadenes d'aquesta versió. On tenim els fitxers amb les cadenes d'aquesta versió?

**Comment by Miroure** [comment]
Penso que caldria que algú amb coneixements informàtics ho coordinés (a mi
allò del GitHub em va molt gros pels coneixements d'informàtica que tinc),
enviant els fitxers als correctors/traductors i que aquests els tornéssim.
I que el coordinador després ho pugés.

El dia 5 d’agost de 2016, 9:40, leixet notifications@github.com ha escrit:

**Comment by deivids84** [comment]
Hola a tots,

Jo no podré ajudar ja que no puc atrapar les línies que surten noves cada setmana. La traducció està feta a corre-cuita i via traductor de Google, ja que traduir unes 300.000 línies amb 5 mesos (Octubre 2015 - Febrer 2016) era l'única via que vaig veure possible. Em va semblar que estaria bé poder-ho compartir i va ser quan em vaig posar en contacte amb l'administrador de Xiaomi.eu.  

Des de febrer em vaig posar a corregir errors amb l'ajuda d'en Jordi i intentar mantenir al dia ja amb traduccions més ben fetes. 

Al Juny en Miquel em va ensenyar que hi havia unes normes de Softcatalà i des de llavors ho faig amb aquesta base, però no tinc temps per corregir les traduccions ja fetes.

Respecta a la base de MIUI 7 ja no existeix, perquè no es faran noves Roms amb aquesta versió i les que existeixen no és tornaran a compilar.

A mi va millor si la traducció és pujà directament a Github, a la seva web hi ha tutorials, però si algú prefereix passar-me el fitxer a mi no hi tinc cap problema. De fet ara en Jordi està treballant sobre els fitxers de la Galeria i un cop acabats m'ho farà arribar.
Si algú està interessat a fer-ho així només cal que em digui que vol traduir, un correu i li faig arribar els 2 documents.

Salutacions

**Comment by Miroure** [comment]
Penso que caldria deixar estar la versió 7, i dedicar temps només a la 8.
Jo proposo que algú d'aquest grup que entengui el GitHub que m'ho/ens
expliqui amb una sessió de Teamwiever, on per exemple jo, pugui baixar,
modificar i pujar el fitxer corregit.
Doncs he provat de seguir tutorials i ....

El dia 5 d’agost de 2016, 16:58, David Capdevila notifications@github.com
ha escrit:

**Comment by leixet** [comment]
Bé, en algun altre projecte q també estava a github el que hem acabat fent
és utilitzar alguna altra plataforma, tipus transifex o crowdin, més
enfocades a la traducció col·laborativa, pujar-hi els fitxers per
traduir-los allà, i després pujar els fitxers traduïts a github, i
actualitzar-los a mesura q van sortint noves cadenes i les traduïm. L'ideal
és que això ho fes directament l'autor del projecte (en aquest cas xiaomi.eu)
però si no utilizen cap plataforma específica per traducció, ho podem fer
nosaltres.

Comento quatre coses amb els companys de Softcatalà i us dic el què.

Puc coordinar alguna cosa jo, si voleu.

El dia 5 ag. 2016 5:39 p. m., "Miroure" notifications@github.com va
escriure:

**Comment by leixet** [comment]
Companys, em miro això i a veure si puc posar-ho en marxa: https://www.transifex.com/blog/2013/github-transifex-integration/

Crec que a en Robert (i a tots plegats) ens pot anar molt bé traduir directament a transifex (i que tot estigui sincronitzat automàticament a github).

Miro  de tenir-ho llest aquesta setmana que ve.

**Comment by leixet** [comment]
Veig que per muntar això necessitaré poder afegir Service Hooks al repo.

> 3) The ability to add Service Hooks to your Github repo.

Pots donar-m'hi aquest accés, @deivids84 ?

**Comment by deivids84** [comment]
Ja hi tens accés @leixet

**Comment by leixet** [comment]
Perfecte! A veure si me'n surto...

**Comment by leixet** [comment]
Ho tinc gairebé a punt. M'estic perdent una mica a l'hora d'introduir els "resources" a transifex. A veure si em pots donar un cop de mà @deivids84 

Per una banda tinc el projecte a Transifex creat, el servidor a Amazon Web Services en marxa i configurat, i per l'altra tinc el repo del github. La qüestió ara és que al Transifex necessito posar-hi els "resources" originals en anglès (tots els arxius strings.xml i tal). De quin repo els he d'agafar? La gràcia seria que fos el repo que els de Xiaomi.eu van actualitzant amb les noves cadenes i tal. Això ho agafaria el servidor de Amazon Web Services automàticament, cada vegada q hi hagués canvis al repo, i llavors, l'actualització en l'altra direcció la faria el mateix servidor AWS però al repo teu, el català, que és on entenc q els de Xiaomi.eu van agafant les cadenes quan compilen noves versions. No?

El que veig és que crec que per poder agafar els "resources" del repo original en anglès, necessitariem accés admin al repo en questió (per configurar els webhooks q notifiquen els canvis al servidor AWS), la qual cosa no és viable, per tant entenc que caldria configurar-ho sobre el propi repo català. Perquè quan hi ha noves cadenes o strings.xml a xiaomi.eu, aquí al repo català s'actualitzen i apareixen automaticament? O com va?

Disculpa però és que el github i tot això és una mica nou per mi.

També he estat veient que hi ha molts strings.xml que són els espanyols, per traduir al català des de l'espanyol. Clar, això no ens va del tot bé, sobretot si integrem amb Transifex, que espera idioma original anglès.

Sé que sembla molt complicat tot plegat, però si ho aconseguim muntar, val la pena, per com facilitaria tota la feina de traducció, correcció, revisió... i de manteniment de la traducció al llarg del temps.

**Comment by deivids84** [comment]
Doncs jo els fitxers amb anglès els estic agafant de la base de Xiaomi.eu https://github.com/Acid-miuipolskapl/v8-XML-Compare i concretament de la carpeta de Gemini que correspon el Mi5, un dels més moderns i complets.

Els canvis els has d'introduir manualment, a més hi ha línies que no s'han de traduir, ja que afecten al funcionament de la ROM. Normalment s'identifiquen perquè comencen amb minúscula

**Comment by leixet** [comment]
Ok. Ho deixo córrer, el sistema no està pensat per tenir tants arxius strings.xml diferents i separats en carpetes. He suat molt i no ho he aconseguit. Així que res, traduirem sobre el github, què hi farem...

El que no m'acaba d'agradar és això de tenir arxius amb cadenes en castellà... podríem endreçar-ho tot i deixar-hi tots els arxius originals en anglès, mantenint les traduccions q ja tenim?

Per altra banda, quan hi ha noves cadenes o nous fitxers de cadenes, aquí al repo del @deivids84 s'actualitza sol o s'han d'agafar manualment del repo que indicaves en anglès? Per altra banda, segur q només cal agafar els fitxers de Gemini? Sí, el Mi5 és el que tinc jo, però llavors els altres models quedaran ben traduïts també? No ho acabo d'entendre.

Bé, en tot cas, ens hi posem ja que si no passarà l'agost i no haurem fet res. @Miroure , si vols anar-nos enviant els arxius q tradueixis/corregexis, anem incorporant-los. Si no també puc intentar mostrar-te com fer-ho per github, tot i q tampoc en sóc un expert.

Us sembla si ens trobem en aquest grup de Telegram per gestionar-ho tot plegat, repartir-nos els arxius a traduir, coordinar les actualitzacions o ajudar-nos com deia en @Miroure? Us deixo l'enllaç al grup que he creat i així parlem més bé, d'acord?

https://telegram.me/joinchat/AEmiNz60ZibbV98FJErmcA

Fins ara!

**Comment by deivids84** [comment]
Els canvis s'han de introduir manualment i per fer-ho perfecte s'hauria de d'incloure totes les línies de totes les carpetes. Però com que això és molt complicat i porta molta feina, el més òptim és traduir la carpeta de Gemini què és un dels telèfons més complets. Jo tinc un Mi Note i no he tingut cap problema. 

Jo com vaig comentar des del principi no hi podré participar. Passaré l'enllaç a @JS67 per si vol unir-se.

**Comment by Miroure** [comment]
Jo personalment no tinc cap Xiaomi (sí que tinc familiars que en tenen i no
és cap dels models que comenteu, de fet és un Redmi 3), però considero que
caldria que els fitxers traduïts fossin aprofitables pel màxim de
dispositius i versions (si és que es pot).

Per tant agrairé que trieu un directori (Settings, ... o el que sigui) i
digueu com el repartim per revisar-lo, corregir-lo. Quan acabem en fem un
altre i anar fent.

No tinc Telegram. Només tinc un telèfon (és d'empresa i ús personal al
mateix temps) i no puc tenir-lo.

El dia 9 d’agost de 2016, 6:57, David Capdevila notifications@github.com
ha escrit:

**Comment by leixet** [comment]
Vaja, doncs potser aniria bé parlar per email enlloc de per aquí. El del Robert ja el tinc que el vas posar més amunt. Després t'envio un mail. 

Us comento les novetats per aquí. He aconseguit pujar els fitxers de cadenes a Crowdin, que sí que m'ha deixat pujar-los tots de cop i els manté ordenats en les carpetes.

Hi he pujat les cadenes originals del repo de referència q comentava en David, i després hi he pujat les traduccions ja fetes al repo del David, que ha auto-vinculat correctament, crec. Feu-hi un cop d'ull, i si us sembla bé, potser podem treballar en aquest entorn, més amigable i òptim per traducció. Què us sembla? 

https://crowdin.com/project/miui-8-xiaomieu/ca#

Només cal que us hi registreu com a usuaris, gratuïtament i us afegiré com a traductors/revisors etc. Ja m'han aprovat el projecte com a projecte Open Source i per tant també és gratuït tenir-lo allà.

@deivids84  si veus algun arxiu xml que no s'ha de traduir, el treiem, que n'hi ha algun que el contingut és molt estrany (algun surt tot en xinès)  i he suposat que no s'ha de tocar res.

@Miroure mira si a settings surten les cadenes com les vas traduir tu. Sinó em passes l'arxiu i el penjo a crowdin que ho actualitzarà sol.

Per cert @deivids84 , segons el manual per traductors q enllacen a Xiaomi.eu, el repo ha de tenir una carpeta main i una devices, la main amb els arxius de cadenes comuns i la devices amb les carpetes de cada dispositiu amb les cadenes específiques d'aquests. Però aquí tenim carpeta main i carpeta extra. Això ja no és així? Ha canviat? (veig q el manual és realment antic, parla de MIUI 2, de MIUI 4...). En saps res? O ho posem tot a main i "tirem pel dret", no?

![img_20160809_092017](https://cloud.githubusercontent.com/assets/6556383/17507920/866d7340-5e12-11e6-9108-32a510a7a8ec.jpg)

**Comment by deivids84** [comment]
La estructura ha de ser carpeta main i carpeta extra, que es la que ténen avui en dia les ROM de MIUI. 

És important no traduir línies que comencen en minúscula i quan s'actualitza algun arxiu a Github, revisar que no hi hagi cap error des de l'enllaç que hi ha a l'arxiu Readme. 

A vegades els errors poden tardar fins a mitja hora a aparèixer. Si hi ha algun error simplement la gent de Xiaomi.eu no inclouen l'idioma en la propera actualització.

**Comment by leixet** [comment]
Pots posar un exemple de línia que comenci amb minúscula i no s'hagi de traduir?

**Comment by deivids84** [comment]
Per exemple aquesta de MiuiGallery

<string name="contrast_polymorphism">photoeditor_effect_contrast</string>

**Comment by deivids84** [comment]
"<string name="contrast_polymorphism">photoeditor_effect_contrast</string>"

**Comment by leixet** [comment]
D'acord. Entesos. Ja ho anirem veient en el Crowdin també.

Si hi entreu, ja està tot en marxa. He aconseguit vincular-ho a un fork q he fet del repo original en anglès (però deixant només la carpeta gemini pq sino era impossible de gestionar tants arxius), de manera que quan hi hagi noves cadenes, només actualitzant el repo fork aquest, el crowdin agafarà les noves cadenes. De la mateixa manera, a mesura que anem acabant de traduir arxius, el crowdin els actualitza al mateix repo meu, en una branch diferent. Haurem de mirar llavors de passar manualment els arxius traduits al repo del @deivids84 i que així els de xiaomi.eu ho agafin. Serà en aquest moment que comprovarem q no hi hagi errors, mitjançant l'enllaç del readme, com comentava en David.

Crec que ja podem fer bona feina ara. Jo ja he començat. Podeu posar-vos-hi vosaltres també aquí:
https://crowdin.com/project/miui-8-xiaomieu/invite

Us sembla bé? Posem aquest enllaç a la portada d'aquest repo de manera que si arriba algu des dels forums de xiaomi.eu amb ganes de col·laborar, arribi a crowdin?

**Comment by Miroure** [comment]
Jo ja m'he registrat al Crowdin. M'has d'autoritzar?
Al vespre quan arribi a casa miraré el fitxer Settings que havia començat a
traduir.

El dia 9 d’agost de 2016, 17:01, leixet notifications@github.com ha
escrit:

**Comment by JS67** [comment]
Hola a tots
Jo estic traduint la Galeria, vaig per la línia 600 i espero acabar-la com
a molt dijous.
No tinc molta idea d'informàtica però sí moltes ganes en col·laborar.
Tingueu paciència i em dieue què haig de fer.
Quan acabi la Galeria,  si no sé on pujar l'arxiu us l'enviaré de moment
per mail i ja m'explicareu, d'acord?
Salutacions,

El dia 09/08/2016 17.01, "leixet" notifications@github.com va escriure:

D'acord. Entesos. Ja ho anirem veient en el Crowdin també.

Si hi entreu, ja està tot en marxa. He aconseguit vincular-ho a un fork q
he fet del repo original en anglès (però deixant només la carpeta gemini pq
sino era impossible de gestionar tants arxius), de manera que quan hi hagi
noves cadenes, només actualitzant el repo fork aquest, el crowdin agafarà
les noves cadenes. De la mateixa manera, a mesura que anem acabant de
traduir arxius, el crowdin els actualitza al mateix repo meu, en una branch
diferent. Haurem de mirar llavors de passar manualment els arxius traduits
al repo del @deivids84 https://github.com/deivids84 i que així els de
xiaomi.eu ho agafin. Serà en aquest moment que comprovarem q no hi hagi
errors, mitjançant l'enllaç del readme, com comentava en David.

Crec que ja podem fer bona feina ara. Jo ja he començat. Podeu posar-vos-hi
vosaltres també aquí:
https://crowdin.com/project/miui-8-xiaomieu/invite

Us sembla bé? Posem aquest enllaç a la portada d'aquest repo de manera que
si arriba algu des dels forums de xiaomi.eu amb ganes de col·laborar,
arribi a crowdin?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/deivids84/MA-XML-8.0-CATALAN/issues/33#issuecomment-238581594,
or mute the thread

**Comment by leixet** [comment]
@Miroure en principi no t'he d'autoritzar si has fet servir aquest últim enllaç q acaba en "invite". No t'hi veig, així que torna-ho a provar. Hi ha un altre company q ja ha fet servir l'enllaç i està dins, ja.

Per cert! He incorporat les cadenes en espanyol per tenir-les de referència quan l'original estigui en xinès o no sigui gens clar, d'acord? Al crowdin va molt bé perquè pots consultar la memòria de traduccions del propi idioma, o també veure les traduccions d'altres (en aquest cas de l'espanyol).

**Comment by leixet** [comment]
Perfecte @JS67. L'arxiu de la galeria un cop traduït el pots adjuntar en un comentari d'aquests mateix, o enviar-me'l per mail a leixet@yahoo.ca i jo l'incorporaré al Crowdin. Si vols seguir amb altres cadenes entra al projecte de Crowdin i segueix allà, que és molt més còmode! https://crowdin.com/project/miui-8-xiaomieu/invite

**Comment by JS67** [comment]
Ok, m'acabo d'afegir al projecte, m'hi veus? i ja hi incorporaré el fitxer.
Perfecte! 👍

El dia 09/08/2016 18.01, "leixet" notifications@github.com va escriure:

**Comment by leixet** [comment]
Si, perfecte @JS67 t'hi veig! Ja pots traduir allà el què vulguis.

Per altra banda, per incorporar el fitxer de la galeria, ho hauré de fer jo em sembla.

**Comment by JS67** [comment]
D'acord  Aleix
Tenim molta feina per endavant...
😂😂😂😂

El dia 09/08/2016 18.07, "leixet" notifications@github.com va escriure:

**Comment by Miroure** [comment]
Em cal ajuda. M'he registrat al crowdin, però no veig que pugui editar..
Què he de fer?

2016-08-09 18:09 GMT+02:00 JS67 notifications@github.com:

**Comment by Miroure** [comment]
Suposo que he entrat, però no en tinc ni idea de com funciona.
Com es fa per veure les strings ja traduïdes i que voldria corregir?

Et va bé de fer una sessió de Teamwiever i m'ho ensenyes?

El dia 9 d’agost de 2016, 17:58, leixet notifications@github.com ha
escrit:

**Comment by Miroure** [comment]
Suposo que he entrat, però no en tinc ni idea de com funciona.
Com es fa per veure les strings ja traduïdes i que voldria corregir?

Et va bé de fer una sessió de Teamwiever i m'ho ensenyes?

El dia 9 d’agost de 2016, 17:58, leixet notifications@github.com ha
escrit:

**Comment by leixet** [comment]
Vinga va @miroure. Deixa'm instalar el TeamViewer...

**Comment by Miroure** [comment]
no cal que l'instal·lis, només executa'l

2016-08-09 18:51 GMT+02:00 leixet notifications@github.com:

**Comment by leixet** [comment]
Fet. He creat un Meeting presentació:

Please join the meeting, by clicking on this link:
http://go.teamviewer.com/v11/m82133788

Meeting ID: m82-133-788

**Comment by Miroure** [comment]
Bon dia
Adjunto el fitxer Strings del directori Settings de la versió 8. Hi ha uns
450 línies traduïdes/corregides (fins que surten les que són en anglès)
perquè es pugin al Crowdin.

2016-08-09 19:00 GMT+02:00 leixet notifications@github.com:

**Comment by leixet** [comment]
Ep @Miroure, deus haver adjuntat el fitxer al correu electrònic que has enviat contestant als missatges del fil, però per a què el rebem, has de venir a la pàgina web del github, on hi ha aquest fil de comentaris sobre l'issue q vas crear fa mesos, i adjuntar-lo al formulari que hi ha a sota de tot per escriure comentaris, on diu "Attach files by dragging & dropping, selecting them, or pasting from the clipboard."

Prova accedint-hi en aquest enllaç: https://github.com/deivids84/MA-XML-8.0-CATALAN/issues/33#issuecomment-238857484

**Comment by leixet** [comment]
Si de cas, també podeu enviar-me els fitxers (o qualsevol dubte o el que sigui) a aleix@softcatala.org

D'acord @Miroure i @JS67 ?

**Comment by Miroure** [comment]
El fitxer que he adjuntat és un que havia començat a corregir/traduir que
m'havia enviat en David i que ahir vam parlar que t'enviaria perquè el
pugessis.
Jo la veritat no en tinc ni idea d'això que dius de pujar-lo al GitHub, i
si ho vaig fer no sé ni el que feia.
T'envio el fitxer al teu correu.

2016-08-10 16:10 GMT+02:00 leixet notifications@github.com:

**Comment by JS67** [comment]
Hola,
Jo, de moment, enviaré el fitxer Galeria,  que ja tinc quasi enllestit, per
correu. Fins quan hi ha temps per fer-lo arribar?
El proper ja miraré de pujar-lo a la plataforma, però aquest ja el tenia
començat.
Salutacions,

El dia 10/08/2016 16.49, "Miroure" notifications@github.com va escriure:

**Comment by leixet** [comment]
Tranquil @JS67, no hi ha cap pressa. Anem fent al ritme que puguem cadascú.

Pel que fa al proper, més que pujar-lo a la plataforma, la idea és que el tradueixis/corregeixis a la pròpia plataforma Crowdin, sense pujar ni baixar res. Si necessites un cop de mà per veure com funciona Crowdin, fem un TeamViewer, que amb en @Miroure va anar molt bé.

**Comment by JS67** [comment]
Ok! Tenim pendent doncs un TeamViewer.
Gràcies, Aleix

El dia 10/08/2016 17.19, "leixet" notifications@github.com va escriure:

Tranquil @JS67 https://github.com/JS67, no hi ha cap pressa. Anem fent al
ritme que puguem cadascú.

Pel que fa al proper, més que pujar-lo a la plataforma, la idea és que el
tradueixis/corregeixis a la pròpia plataforma Crowdin, sense pujar ni
baixar res. Si necessites un cop de mà per veure com funciona Crowdin, fem
un TeamViewer, que amb en @Miroure https://github.com/Miroure va anar
molt bé.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/deivids84/MA-XML-8.0-CATALAN/issues/33#issuecomment-238900801,
or mute the thread

**Comment by leixet** [comment]
Quan tu diguis @JS67. Si m'envies un mail a aleix@softcatala.org ja podrem comunicar-nos tots tres (@miroure tu i jo) per mail, i potser guanyarem amb fluidesa. Ara mateix tinc algunes qüestions terminològiques a comentar-vos, a veure què opineu...

**Comment by leixet** [comment]
Bones notícies companys! Hi ha moltes cadenes que són exactament com a la versió stock d'Android, i per tant la Memòria de Traducció del Crowdin les recull, i són correctes perquè el Crowdin beu de les memòries de traducció de Softcatalà, així que en els casos que veieu una proposta de la memòria de traducció del crowdin que digui "Global TM, Perfect match" o "Global TM, 100% match", mireu-la bé perquè segurament ja serveix i no cal que escriviu res més! Genial!

**Comment by leixet** [comment]
Bé, ja hem introduït, per provar si tot va bé, un primer fitxer revisat de dalt a baix. Els 3 xml de la carpeta Bluetooth.apk. Comprovat amb l'xml checker de l'enllaç del readme a la portada no dona cap error, així que a veure si a la propera build l'incorporen i podem veure si tot va correctament. Seguim traduint a Crowdin. Recordo els enllaços per si algú es vol incorporar a la feina o al debat terminològic:

Entrar al projecte a Crowdin: https://crowdin.com/project/miui-8-xiaomieu/invite
Entrar al grup de Telegram: https://telegram.me/joinchat/AEmiNz60ZibbV98FJErmcA
Contactar per email: aleix@softcatala.org

**Comment by JS67** [comment]
Pensava acabar avui la Galeria però no podré. He revisat 800 línies de
1.100. Si t'envio el fitxer si encara el podem incorporar? O ja espero a
acabar-lo? És que era molt llaaaaarrrgggg 😓😎😂. Per altra banda, quan
comenci un altre, ja ho faré per Crowdin.

El dia 11/08/2016 15.16, "leixet" notifications@github.com va escriure:

**Comment by leixet** [comment]
Ei, cap problema si m'ho vols enviar a mitges. Amb en miroure ho vam fer així, vam pujar el que tenia fet de Settings.apk i ara ja pot seguir a Crowdin.

Si vols envia'm l'arxiu de la Galeria i el pujo, ja vigilaré de només pujar fins la línia que em diguis que està feta.

**Comment by JS67** [comment]
D'acord. He fet fins la línia 815.
Espero que estigui bé (és el primer que faig....😀)
  MiuiGallery Català.xml
https://drive.google.com/file/d/0B91Z9UfOtrC4cE9zX2lZQW1ZMVJMRHlpWE9wLU53REdCRmtz/view?usp=drivesdk

El dia 11/08/2016 16.20, "leixet" notifications@github.com va escriure:

**Comment by leixet** [comment]
Incorporat! Gràcies @JS67!

Ara si vols fes-hi un cop d'ull al Crowdin, (https://crowdin.com/translate/miui-8-xiaomieu/22088/en-ca) hauries de veure la teva feina incorporada allà, i seguir corregint, si vols. Aquest i la resta de fitxers! hehe

Merci!

**Comment by JS67** [comment]
Bon dia,

He entrat a Crowdin i he vist el fitxer. Perfecte! Entenc que el quadret
verd ja està traduït i manquen els quadrets vermells. És molt més fàcil per
aqui!!!! Era una "matada" anar copiant les línies del fitxer original al
català (o potser no ho sabia fer d'una forma més fàcil....hahahaha)
Aniré fent per aquí, continuo amb la MiuiGallery, haig de fer també
"arrays" i "plurals"? perquè fins ara només feia "strings"....
A més, n'hi ha amb quadrets vermells que no cal traduir, com són les
ciutats xineses, cal fer com si es tradueixen per a donar-ho com a bo tal
com està?
I en cas de  "%1$s" no cal tocar res, no? es deixa tal com està?

Avui he descarregat la 6.8.11 i he vist que quan carrega la rom a la
pantalla hi surt "Preparant", "Actualitzant",....que abans no sortia,
suposo que és part de la tasca que ha fet miroure.
En aquesta nova versió hi ha la possibilitat de fer captura de pantalla amb
els 3 dits i, clar, tot això no surt traduït. Si hi ha gaires novetats, mai
atraparem la traducció total....bufff!!!  ;-)

Molt bé! Vinga! Endavant!

Salutacions,

**Comment by Miroure** [comment]
Diria que no he sigut jo, doncs jo ho hauria traduït per: S'està
preparant,...

El dia 12 d’agost de 2016, 8:56, JS67 notifications@github.com ha escrit:

**Comment by JS67** [comment]
Hola, Miquel

Perdó!, vaig llegir que havies traduït "Settings" i pensava que estava
allà, per això ho deia... A mi, però, ja m'està bé  ;-)

Salutacions,

El dia 12 d’agost de 2016, 9:22, Miroure notifications@github.com ha
escrit:

**Comment by deivids84** [comment]
Jordi, a mi ara em surt el menú del navegador en anglès en aquesta última actualització. A tu també?
Actualitzant i preparant ho vaig traduir jo. No ho vaig traduir com diu en Miquel perquè sempre intento respectar el màxim la llargada de l'original per evitar frases tallades.

**Comment by JS67** [comment]
Hola David
A mi el navegador ja fa 2 roms enrere que em surt en anglès.
A mi em sembla bé "Actualitzant i preparant", ho prefereixo a que es talli
la frase.
Ens abandones?
Salutacions,

El dia 12 d’agost de 2016, 13:14, David Capdevila notifications@github.com
ha escrit:

**Comment by deivids84** [comment]
Hola Jordi,
D'acord, així alguna cosa vaig tocar.  😀
Ara estic passant una temporada a Canadà i aprofitant el màxim el temps. A la tornada a mitjans de setembre si la feina m'ho permet, intentaré tornar-hi, però amb la gran feina que ha fet l'Aleix estic segur que no em trobaràs pas a faltar.

Salutacions

**Comment by JS67** [comment]
D'acord, David

El dia 12/08/2016 13.43, "David Capdevila" notifications@github.com va
escriure:

**Comment by leixet** [comment]
Ep, el tema dels gerundis "Actualitzant, preparant..." a Softcatalà preferim respectar el "S'està preparant..." i després veure en els casos que no hi cap la cadena, buscar la solució (i si cal, sí, deixar-ho en "Preparant...")

Per altra banda, el nou navegador és probable q sigui un nou arxiu de cadenes, pq sembla una nova versió, no? 

Arrays i plurals també cal traduir-ho. Sempre mirant q no hi hagi cadenes q no s'hagin de traduir, com les q deia en David, q comencen en minúscula (i normalment sense espais entre paraules). Aquestes i les q són en xinès a Crowdin  s'han de copiar igual q la original. I els %1$s i demés, s'han de posar igual en el lloc q pertoqui en català.
