### ISSUE TITLE
FC en l'última versió 6.11.24 en el Launcher (En Omega)

### ISSUE THREAD

**Issue by Algiam** [deivids84/MA-XML-7.0-CATALAN#38]
Bones,

He instal.lat aquesta versió i dona un FC el launcher i no es pot usar. En quant ho poses en espanyol funciona correctament. Ho he provat varis cops cremant la imatge baixada de diferents servidors per si l'arxiu estava corrupte.

Salutacions i gràcies.

**Comment by lavinski7** [comment]
Efectivament hi ha un bug greu en aquesta Rom, sorprenentment la primera
que va penjar @ingbrzy funcionava be, es la reuploaded version la que no
funciona

Salut

El dia 1 des. 2016 10:42, "Algiam" <notifications@github.com> va escriure:

**Comment by SrLluny** [comment]
El mateix en la 6.12.1
Jo tinc el Redmi 3 Prime (ido)
