### ISSUE TITLE
FC en la darrera versió 6.12.1 en el Launcher (Ido) 

### ISSUE THREAD

**Issue by SrLluny** [deivids84/MA-XML-7.0-CATALAN#39]
Des de la ROM 6.11.24, segona fornada, no podem tindre el mòbil en català, Redmi 3 Pro/Prime, perquè el llançador directament falla i deixa la pantalla en negre. Només pots anar a opcions i apagar o encendre el mòbil.
Hem de dur el mòbil en castellà o anglés. Quan s'arreglarà la cosa? Alguna idea?
No dur el mòbil en català em crema.

**Comment by jconstanti** [comment]
És tracta d'un un error ja conegut que se'ns ha passat en aquesta ROM. Ara hem d'esperar la propera ROM setmanal de cada matinada de divendres

**Comment by SrLluny** [comment]
Perfecte. 
Moltíssimes gràcies!

**Comment by Algiam** [comment]
Moltes gràcies pel vostre esforç!!!!!
